### ISSUE TITLE
SSH key name for different learning paths

### ISSUE THREAD

**Issue by odidev** [ArmDeveloperEcosystem/arm-learning-paths#108]
I have raised the [PR](https://github.com/ArmDeveloperEcosystem/arm-learning-paths/pull/94) for changing `key_name = “id_rsa”` and linked all the ssh key generation with a ssh document present in install-guides. 

A new [PR](https://github.com/ArmDeveloperEcosystem/arm-learning-paths/pull/95) which was raised and merged for mysql learning path. Key name in that is given as `mysql_key` and undone the previously merged changes of mysql learning path. 

Can you please let me know if I need to follow the changes done in mysql learning path for all learning path or can I continue using `key_name = “id_rsa”` for future learning paths?

**Comment by armflorentlebeau** [comment]
Hi,
I've been reviewing the mysql Learning Path while you were pushing your changes so I had to merge them. I may have kept the name mysql_key but don't mind reverting to id_rsa to be consistent with the other articles.
I will make a PR and let you know.
Florent

**Comment by odidev** [comment]
Thanks for the clarification. If required, I can raise PR for the same.
