### ISSUE TITLE
KleidiAI and matrix multiplication

### ISSUE THREAD

**Issue by rwalkr** [ArmDeveloperEcosystem/arm-learning-paths#1120]
The description of FMOPA on https://learn.arm.com/learning-paths/cross-platform/kleidiai-explainer/page1/:

> FMOPA: This instruction stands for Floating-point outer product and accumulate. It is included in the Arm Scalable Vector Extension 2 (SVE2). The single precision FMOPA variant enables optimized matrix multiplication on 32-bit numbers. View the FMOPA documentation [here ](https://developer.arm.com/documentation/ddi0602/2023-12/SME-Instructions/FMOPA--non-widening---Floating-point-outer-product-and-accumulate-?lang=en) .

incorrectly says it's part of SVE2 - it's SME

**Comment by pareenaverma** [comment]
Thanks @rwalkr for spotting this. Fixed in PR #1122.
