### ISSUE TITLE
Using the command line

### ISSUE THREAD

**Issue by agmessier** [ArmDeveloperEcosystem/arm-learning-paths#1245]
I'm trying to follow the instructions on this page using Ubuntu (tried both 22.04 and 24.04).  Last week the procedure worked just fine for me and was hassle free.

https://learn.arm.com/learning-paths/microcontrollers/uvprojx-conversion/how-to-2/

Now I can't get it to work, as I hit a roadblock at every step.  First, at step 3 I get an error "vcpkg: command not found"

Then I discovered that there's a vcpkg executable in the ~/.vcpkg directory (I didn't have to specify the path last week), and started running the commands from that path.

When I run step 4, I get the error "no postscript file: run vcpkg-shell with the same arguments".  I don't see a vcpkg-shell executable anywhere.

When I try step  5, I get "uv2csolution: command not found".  Likewise, I don't know where to find uv2csolution, or if it's just because the previous step failed.

I've tried this on fresh installations of Ubuntu every time.  I wonder if the .vcpkg-init.sh script has been changed or something else in the package.  In any case, I need help getting this to work.

Thanks,
Andy

**Comment by pareenaverma** [comment]
@KeilChris - can you please help look into this issue?

**Comment by KeilChris** [comment]
Yes, will do. Microsoft has changed the command line. You need to call vcpkg-shell (refer to https://github.com/microsoft/vcpkg-tool/pull/1442).

**Comment by KeilChris** [comment]
Corrected by https://github.com/ArmDeveloperEcosystem/arm-learning-paths/pull/1255

**Comment by agmessier** [comment]
Hi Chris,

Thanks for getting to this so quickly!  This seems to work now if I call vcpkg-shell.  The procedure will need to be updated accordingly.

**Comment by KeilChris** [comment]
Great that it works for you again!
