### ISSUE TITLE
Build and run the Arm CCA stack on an Arm FVP

### ISSUE THREAD

**Issue by cezane** [ArmDeveloperEcosystem/arm-learning-paths#1302]
When running the command to run the binaries on the FVP:

    ./model-scripts/aemfvp-a-rme/boot.sh -p aemfvp-a-rme shell

I am getting the following error message:

>  ./model-scripts/aemfvp-a-rme/boot.sh -p aemfvp-a-rme shell
>  ERROR: you should set variable MODEL to point to a valid FVP model binary.
>  Current MODEL value is "~/cca-stack/Base_RevC_AEMvA_pkg/models/Linux64_GCC-9.3/FVP_Base_RevC-2xAEMvA"

**Comment by pareenaverma** [comment]
Hi @cezane - I'm unable to reproduce the issue you are seeing. Your MODEL variable is correct and pointing to the x86_64 executable for the FVP. Can you please check that your FVP model binary was downloaded correctly and exists in that location?
