### ISSUE TITLE
LP Next Steps: Arm IP tag leads to 404

### ISSUE THREAD

**Issue by armflorentlebeau** [ArmDeveloperEcosystem/arm-learning-paths#35]
When completing a learning path until "Next Steps" in "Explore Tags", the tags related to Arm IP lead to a page not found error.
Seen with "Neoverse" tag in learning-paths/server-and-cloud/codec/_next-steps/
and with "Cortex-M" tag in learning-paths/microcontroller/cmsis-dsp-tests/_next-steps/

**Comment by zachlas** [comment]
I modified the config.toml to reroute armip tags properly. Should work fine after the next PR!

**Comment by jasonrandrews** [comment]
Confirmed fixed
