### ISSUE TITLE
Python for Windows on Arm

### ISSUE THREAD

**Issue by linuxrebel** [ArmDeveloperEcosystem/arm-learning-paths#521]
It seems that the platform module for python 3.11 compiled for ARM is returning a hard coded release version.  

python3.11 compiled for ARM
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:44:02) [MSC v.1934 64 bit (ARM64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.uname()
uname_result(system='Windows', node='jsam', **release='10**', version='10.0.25967', machine='ARM64')

Python 3.12 pulled from Windows store
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.uname()
uname_result(system='Windows', node='jsam', **release='11',** version='10.0.25967', machine='ARM64')
>>>

running uname.py

PS C:\Users\james> python .\uname.py
Python version 3.11.1
Machine is Windows 10 ARM64

PS C:\Users\james> py.exe .\uname.py
Python version 3.12.0
Machine is Windows 11 ARM64

**Comment by jasonrandrews** [comment]
I was able to confirm the issue with Python 3.11. It appears to be fixed in version 3.12
You can download at https://www.python.org/ftp/python/3.12.0/python-3.12.0-arm64.exe and this version correctly prints Windows 11 ARM64. 

We will update the install guide for version 3.12. 

Thanks for the information.

**Comment by linuxrebel** [comment]
No problem. Thanks for the update.

**Comment by pareenaverma** [comment]
The install guide has been updated for version 3.12
Thanks for reporting. Closing the issue now.
