### ISSUE TITLE
Prepare AVH instances of Raspberry Pi 4

### ISSUE THREAD

**Issue by zachlasiuk** [ArmDeveloperEcosystem/arm-learning-paths#539]
"Settings > Personal Access Tokens, click on Generate new token, and save the token locally."

This line does not specify what permissions should be granted to the new token, nor what type of token (classic vs fine-graned tokens). Will either work?

**Comment by pareenaverma** [comment]
Either token will work. We shall clarify in the next iteration of the learning path.
