### ISSUE TITLE
Feedback - Arm Software Licensing

### ISSUE THREAD

**Issue by martin-chris** [ArmDeveloperEcosystem/arm-learning-paths#556]
The FlexNet Publisher setup instructions on learn.arm.com: https://learn.arm.com/install-guides/license/flexnet/ have the user run "armcc --vsn" which is the old arm v5.x compiler that has been deprecated and no longer installed by default with DS.

**Comment by pareenaverma** [comment]
Hi @martin-chris - thanks for reporting this. We could highlight an older version of a tool that doesn't support UBL.
There’s a table [here](https://learn.arm.com/install-guides/license/) that lists when UBL was supported.

For example, we could change it to say:

To verify that the license is set up correctly, execute an Arm tool that does not support user-based licensing. For example, if you are using Arm Compiler for Embedded 6.17, run:

armclang --vsn

Does this help address the issue?

We chose armcc (while being deprecated it also doesn't support any UBL) and makes for a simple example.

**Comment by martin-chris** [comment]
Thanks Pareena.  This will help, but would not completely solve the issue.  I understand why we chose to test with a version of the tool that only supports floating, but today customers are still installing tools that support both floating and UBL, so requiring them to test with an older version than they might currently be using is not user friendly.  

We need to show how to test that it has correctly checked out a license with armclang version 6.20 and to show that it is not using UBL.

**Comment by martin-chris** [comment]
@pareenaverma Maybe we should simply show checking out a floating license with the armlmdiag tool that comes with the flexnet publisher download.  This way there is no additional tool (current version or legacy version) that needs to be installed...

`1) Floating license (license server running at: 27008@localhost)
----------------------------------------------------------------
*Checkout a license for feature f1, version 1.0
    $ armlmdiag -L 27008@localhost --feature f1 --version 1.0`

**Comment by pareenaverma** [comment]
Hi @martin-chris - we've addressed this issue and you can now check the live updates here https://learn.arm.com/install-guides/license/flexnet/
