### ISSUE TITLE
Explanations

### ISSUE THREAD

**Issue by merflix** [ArmDeveloperEcosystem/arm-learning-paths#607]
Please give more explanations.
For example, should I always delete what I have build with bitbake for futher use or not?
This takes hug amount of space on a disk (40G and plus)

**Comment by pareenaverma** [comment]
Hi @merflix thank you for reporting this. Could you please specify which learning path or install guide are you particularly referring to in this case? We'd be happy to add more details. Thank you.

**Comment by pareenaverma** [comment]
Closing this as there has been no response on details.
