### ISSUE TITLE
Get started with Yocto Linux on Qemu

### ISSUE THREAD

**Issue by richardh538** [ArmDeveloperEcosystem/arm-learning-paths#672]
| /home/huberz/repos/poky/build-qemu-arm64/tmp/work/x86_64-linux/libdnf-native/0.66.0-r0/git/libdnf/repo/../conf/ConfigRepo.hpp:91:45: error: template argument 1 is invalid
|    91 |     OptionChild<OptionNumber<std::uint32_t> > & deltarpm_percentage();
|       |                                             ^
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
ERROR: Task (virtual:native:/home/huberz/repos/poky/meta/recipes-devtools/libdnf/libdnf_0.66.0.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2175 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  virtual:native:/home/huberz/repos/poky/meta/recipes-devtools/libdnf/libdnf_0.66.0.bb:do_compile
Summary: There were 4 WARNING messages.
Summary: There was 1 ERROR message, returning a non-zero exit code.

Broken.

**Comment by jasonrandrews** [comment]
@richardh538 I'm going to close this issue. The instructions have been reviewed, some minor updates were made on the website, but nothing significant was changed. The build is challenging in terms of disk space, processing performance, and memory.
