### ISSUE TITLE
Debug connection with Arm DSTREAM

### ISSUE THREAD

**Issue by rkumari33** [ArmDeveloperEcosystem/arm-learning-paths#730]
Hello 
I am trying to configure DStream debug for Flash Loader IAR. I am not able to find any document can I get assistance

**Comment by RonanSynnottArm** [comment]
Flash Loader requires IAR tools. DSTREAM is not compatible with this.

However equivalent functionality is provided within Arm Development Studio:
https://developer.arm.com/documentation/101470/2023-0/File-based-Flash-Programming-in-Arm-Development-Studio

Which device are you using?

**Comment by rkumari33** [comment]
Hello
Thank you for reply.
The device processor is ARM Cortex M33. We are trying to develop Flash loader for DStream debugger. But I have no document for DStream. Do you have any solution of it.

Thank you
Roshni

**Comment by RonanSynnottArm** [comment]
The above documentation I referenced would be to implement Flash Programming within the Arm Debugger.

There is also an API called RDDI that you could use to create your own stand alone application.
Documentation and some code examples are provided within an Arm Development Studio installation (in \sw\debugger\RDDI folder).

**Comment by rkumari33** [comment]
Just being Clear, I cannot use IAR Workbench with D-Stream

**Comment by RonanSynnottArm** [comment]
You cannot, sorry.

**Comment by rkumari33** [comment]
only ARM Development studio IDE ?

**Comment by RonanSynnottArm** [comment]
Correct

**Comment by rkumari33** [comment]
Thank you, well my project is in IAR how I create the same project in ARM development studio IDE. Is there any site which Can be helpful. I will really appreciate your input.

**Comment by RonanSynnottArm** [comment]
I hope this learning path will help you get started:
https://learn.arm.com/learning-paths/embedded-systems/armds/
