### ISSUE TITLE
Configure and run WSL with various Linux distributions

### ISSUE THREAD

**Issue by mitch-arm** [ArmDeveloperEcosystem/arm-learning-paths#733]
From Windows, bash.exe (or just bash) can be used to run commands in WSL.
You can enter the default WSL distribution by running bash from a Windows Command Prompt:

could be simplified to:

From Windows, Bash can be used to run commands in WSL.
You can enter the default WSL distribution by running bash from a Windows Command Prompt:
...

**Comment by mitch-arm** [comment]
Also could supplement:
"
You can enter the default WSL distribution by running bash from a Windows Command Prompt:
bash.exe 
"
with
"
You can enter the default WSL distribution by running Bash from a Windows Command Prompt:
bash.exe 

You can exit Bash and return back to the Windows Command Prompt with:
exit

**Comment by jasonrandrews** [comment]
@mitch-arm 
Thanks for the suggestions, I will make the changes.

**Comment by jasonrandrews** [comment]
Improvements completed.
