### ISSUE TITLE
How to develop Flash loader using DSTREAM in FPGA 

### ISSUE THREAD

**Issue by rkumari33** [ArmDeveloperEcosystem/arm-learning-paths#740]

**Comment by rkumari33** [comment]
Hello 
Currently I am trying to understand how to develop Flash loader for FPGA using DSTREAM. Can anyone help me with procedures since in IAR the procedure was clear but it's not compatible with DSTREAM debugger, so I am using ARM DEVELOPMENT Studio IDE. Can anyone help me with example or script.

**Comment by RonanSynnottArm** [comment]
The procedure is documented here:
https://developer.arm.com/documentation/101470/2023-1/File-based-Flash-Programming-in-Arm-Development-Studio

There are a few examples supplied with Arm Development Studio.

Go to File > Import > Arm Development Studio > Examples and Programming Libraries, and search for 'flash' in the text box.

Each example has a readme that explains functionality.

**Comment by rkumari33** [comment]
okay let me check thank you
