### ISSUE TITLE
Browsers on Arm

### ISSUE THREAD

**Issue by mitch-arm** [ArmDeveloperEcosystem/arm-learning-paths#836]
Chrome win_arm64 is now available on Stable channel as a Windows native arm64 download: https://www.google.com/chrome/?platform=win_arm64
Version 123.0.6312.86 (Official Build) (arm64)

**Comment by jasonrandrews** [comment]
Thanks @mitch-arm 
I'll update the browsers on Arm install guide.

**Comment by jasonrandrews** [comment]
This has been updated.
