### ISSUE TITLE
Accessing elements of a matrix row_wise using SVE.

### ISSUE THREAD

**Issue by AjaySingh40** [ArmDeveloperEcosystem/arm-learning-paths#905]
Hello all,
Is it possible to access elements of a  matrix row wise using sve. If yes please provide the link for the docs or help me with that .
I didn't find any document for that.
Thank You.

**Comment by jasonrandrews** [comment]
Checking for some info. Also shared on [Arm Discord](https://discord.com/channels/839248077487472640/1029488870766694450/threads/1240785846932734033).

**Comment by AjaySingh40** [comment]
Could you please send me the invite link for Arm Discord .

**Comment by solidpixel** [comment]
For a non-sequential load you would need to use gathers, which SVE supports. This will be less efficient than sequential loads, so it's often faster to transpose an input matrix to avoid the need for gathers.
