### ISSUE TITLE
Feedback - Missing info that it is ONLY x86_64 installation and no ARM64 version

### ISSUE THREAD

**Issue by LDec-AlmostHuman** [ArmDeveloperEcosystem/arm-learning-paths#956]
Hello,

Correct me if I am wrong, but this is Arm Development Studio that does NOT work on ARM64.
--- Host target check...[aarch64]
    The x86_64 installation is not supported for this platform
It doesn't say anywhere that does only run on x86_64.

Happy ARM64 owner :)

**Comment by RonanSynnottArm** [comment]
Hello, LDec-AlmostHuman,

Thank you for your feedback.

The host requirements are described here:
https://developer.arm.com/documentation/101469/latest/Installing-and-configuring-Arm-Development-Studio/Hardware-and-host-platform-requirements

The Arm Compiler for Embedded is available as a standalone download (for AArch64 Linux):
https://developer.arm.com/downloads/view/ACOMPE

Regards, Ronan
